- name: Calculate hosts
  set_fact:
    host_count: "{{ ansible_play_hosts | length }}"
    other_host_ips: "{{ ansible_play_hosts | difference([inventory_hostname]) | map('extract', hostvars, 'ansible_host') | list }}"
    percentage_system_memory_to_use: "{{ max_percentage_used_system_memory | default(0.25)}}"

- name: Set shell commands
  set_fact:
    solo_shell_command: "cockroach start-single-node --certs-dir=certs --advertise-addr={{ ansible_ssh_host }} --cache={{percentage_system_memory_to_use}} --max-sql-memory={{percentage_system_memory_to_use}} --background"
    multi_shell_command: "cockroach start --certs-dir=certs --advertise-addr={{ ansible_ssh_host }} --join={{ other_host_ips| join(',') }} --cache={{percentage_system_memory_to_use}} --max-sql-memory={{percentage_system_memory_to_use}} --background"

- name: Show shell command - start single node
  debug:
    msg: "{{ solo_shell_command }}"
  when: host_count | int == 1 and show_shell_command is defined and  show_shell_command == true

- name: Show shell command - start multiple nodes
  debug:
    msg: "{{ multi_shell_command }}"
  when: host_count | int > 1 and show_shell_command is defined and  show_shell_command == true

- name: Start single node
  shell: "{{ solo_shell_command }}"
  when: host_count | int == 1

- name: Start multiple nodes
  shell: "{{ multi_shell_command }}"
  when: host_count | int > 1