- name: verify connection to all hosts
  hosts: "{% if target is defined%}{{target}}{% else %}all{% endif %}"
  gather_facts: false
  tasks:
    - ping:
  tags:
    - reachable

- name: Synchronize clocks
  hosts: "{% if target is defined%}{{target}}{% else %}all{% endif %}"
  gather_facts: false
  roles:
    - aws-time-sync-service-ubuntu
  tags:
    - synchronize-clocks